"""The fixed test lines of the local planner, in the table frame.

Four sets per arm:
  word     the word "unknown" (assets/site/h0970/unknown_strokes.json: old canvas frame, metres,
           scale 1; 1.10 m wide, x-height 0.12 m, baseline on the seam line y = 1.8153, which is
           arm 31's row).  For another arm it is moved by the difference of the two arms' axes,
           so it sits the same way under that arm.
  corpus   the five drawings of the old bench (aris_sixarm/bench: hatch, scatter, starburst,
           spiral, duotone), old canvas frame, cut to the parts within 0.80 m of the arm's axis.
           Generated by the old code; tests/oracle/make_local_reference.py stores them in
           tests/data/local_corpus.npz.
  lines    200 random straight lines: 120 anywhere in reach, 40 right under the base, 40 along
           the rim of the reach.
  curves   100 random smooth curves: 40 arcs, 30 arcs along the rim, 30 waves (half of them
           under the base).
Random lines and curves are 0.05 to 1.2 m long, on the paper, and within 0.78 m of the axis
(the rim of the reach: at 0.784 m no configuration passes the gates, with or without lean);
their seed is the arm id.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from aris.types import Line

ROOT = Path(__file__).resolve().parents[1]
DATA = Path(__file__).resolve().parent / "data"
WORD_FILE = ROOT / "assets" / "site" / "h0970" / "unknown_strokes.json"
CORPUS_FILE = DATA / "local_corpus.npz"
OLD_TO_TABLE = np.array([-0.9017, -1.81532])       # table = old canvas + this
CANVAS_HALF = np.array([0.9017, 1.81532])
ARMS = {31: 2, 13: 1}                               # arm -> the phase in which it leads
SETS = ("word", "corpus", "lines", "curves")
CORPUS = ("hatch", "scatter", "starburst", "spiral", "duotone")
CORPUS_RADIUS = 0.80
RANDOM_RADIUS = 0.78
WORD_ARM = 31                                       # the arm the word file was laid out for
FIGURE_LINE = "line:any:18"                          # the example of docs/modules/local.md


def _line(lid: str, xy) -> Line:
    xy = np.asarray(xy, float)
    return Line(lid, np.column_stack([xy, np.zeros(len(xy))]), "table")


def word(axis_xy, word_axis_xy) -> list[Line]:
    doc = json.loads(WORD_FILE.read_text())
    shift = OLD_TO_TABLE + (np.asarray(axis_xy) - np.asarray(word_axis_xy))
    return [_line(f"word:{i}", np.asarray(s["pts"], float) + shift)
            for i, s in enumerate(doc["strokes"])]


# --------------------------------------------------------------------------- corpus


def clip_to_disc(xy: np.ndarray, centre, r: float) -> list[np.ndarray]:
    """The parts of a polyline inside a disc, each as a polyline (exact crossing points)."""
    xy = np.asarray(xy, float)
    c = np.asarray(centre, float)
    parts, cur = [], []
    for a, b in zip(xy[:-1], xy[1:]):
        d, f = b - a, a - c
        A, B, C = d @ d, 2 * f @ d, f @ f - r * r
        disc = B * B - 4 * A * C
        if A == 0.0 or disc <= 0.0:
            t0, t1 = (0.0, 1.0) if C <= 0.0 else (1.0, 0.0)
        else:
            t0 = (-B - np.sqrt(disc)) / (2 * A)
            t1 = (-B + np.sqrt(disc)) / (2 * A)
        lo, hi = max(t0, 0.0), min(t1, 1.0)
        if lo >= hi:                                  # this segment is outside
            if cur:
                parts.append(np.array(cur))
                cur = []
            continue
        p, q = a + lo * d, a + hi * d
        if not cur:
            cur = [p]
        elif lo > 0.0:                                # re-entering after leaving
            parts.append(np.array(cur))
            cur = [p]
        cur.append(q)
        if hi < 1.0:
            parts.append(np.array(cur))
            cur = []
    if cur:
        parts.append(np.array(cur))
    out = []
    for p in parts:
        keep = np.concatenate([[True], np.linalg.norm(np.diff(p, axis=0), axis=1) > 1e-12])
        p = p[keep]
        if len(p) >= 2:
            out.append(p)
    return out


def corpus(axis_xy) -> list[Line]:
    if not CORPUS_FILE.exists():
        raise FileNotFoundError(f"{CORPUS_FILE} is missing: run tests/oracle/"
                                "make_local_reference.py (see its docstring)")
    data = np.load(CORPUS_FILE)
    out = []
    for name in CORPUS:
        n = int(data[f"{name}_n"])
        for i in range(n):
            xy = data[f"{name}_{i}"] + OLD_TO_TABLE
            for j, part in enumerate(clip_to_disc(xy, axis_xy, CORPUS_RADIUS)):
                out.append(_line(f"corpus:{name}:{i}:{j}", part))
    return out


# --------------------------------------------------------------------------- random lines


def _ok(xy, axis_xy) -> bool:
    return bool(np.all(np.abs(xy) <= CANVAS_HALF - 0.01)
                and np.all(np.linalg.norm(xy - axis_xy, axis=1) <= RANDOM_RADIUS))


def _unit(t):
    return np.array([np.cos(t), np.sin(t)])


def _straight(rng, axis_xy, kind):
    for _ in range(10_000):
        th = rng.uniform(0, np.pi)
        d = _unit(th)
        if kind == "any":
            length = rng.uniform(0.05, 1.2)
            c = axis_xy + np.sqrt(rng.uniform(0, 0.74 ** 2)) * _unit(rng.uniform(0, 2 * np.pi))
        elif kind == "base":
            length = rng.uniform(0.05, 1.2)
            through = axis_xy + rng.uniform(0, 0.03) * _unit(rng.uniform(0, 2 * np.pi))
            c = through + rng.uniform(-0.5, 0.5) * length * d
        else:                                           # rim
            length = rng.uniform(0.05, 0.4)
            a = rng.uniform(0, 2 * np.pi)
            c = axis_xy + rng.uniform(0.70, 0.77) * _unit(a)
            d = _unit(a + np.pi / 2 + rng.uniform(-0.25, 0.25))
        xy = np.array([c - 0.5 * length * d, c + 0.5 * length * d])
        if _ok(xy, axis_xy):
            n = max(2, int(np.ceil(length / 0.05)) + 1)      # a few points, like a tracer's output
            return xy[0] + np.linspace(0, 1, n)[:, None] * (xy[1] - xy[0])
    raise RuntimeError("no line found")


def _resample(xy, step=0.005):
    s = np.concatenate([[0.0], np.cumsum(np.linalg.norm(np.diff(xy, axis=0), axis=1))])
    u = np.linspace(0, s[-1], max(2, int(np.ceil(s[-1] / step)) + 1))
    return np.column_stack([np.interp(u, s, xy[:, 0]), np.interp(u, s, xy[:, 1])])


def _curve(rng, axis_xy, kind):
    for _ in range(10_000):
        length = rng.uniform(0.05, 1.2)
        if kind == "arc":
            rad = rng.uniform(0.05, 0.5)
            span = min(length / rad, 1.8 * np.pi)
            c = axis_xy + np.sqrt(rng.uniform(0, 0.7 ** 2)) * _unit(rng.uniform(0, 2 * np.pi))
            t = rng.uniform(0, 2 * np.pi) + np.linspace(0, span, 400)
            xy = c + rad * np.column_stack([np.cos(t), np.sin(t)])
        elif kind == "rim":
            rad = rng.uniform(0.70, 0.775)
            t = rng.uniform(0, 2 * np.pi) + np.linspace(0, length / rad, 400)
            xy = axis_xy + rad * np.column_stack([np.cos(t), np.sin(t)])
        else:                                           # wave, half of them under the base
            d = _unit(rng.uniform(0, np.pi))
            e = np.array([-d[1], d[0]])
            amp, waves, phase = rng.uniform(0.01, 0.08), rng.uniform(1, 3), rng.uniform(0, 6.3)
            if kind == "wave_base":
                start = axis_xy + rng.uniform(-0.3, 0.3) * length * d
            else:
                start = axis_xy + np.sqrt(rng.uniform(0, 0.6 ** 2)) * _unit(rng.uniform(0, 6.3))
            base = length
            for _ in range(3):                          # the wave's own length is `length`
                u = np.linspace(-0.5, 0.5, 400) * base
                xy = start + u[:, None] * d + (amp * np.sin(2 * np.pi * waves * (u / base)
                                                            + phase))[:, None] * e
                base *= length / np.linalg.norm(np.diff(xy, axis=0), axis=1).sum()
        if _ok(xy, axis_xy):
            return _resample(xy)
    raise RuntimeError("no curve found")


def random_lines(axis_xy, seed) -> list[Line]:
    rng = np.random.default_rng(seed)
    kinds = ["any"] * 120 + ["base"] * 40 + ["rim"] * 40
    return [_line(f"line:{k}:{i}", _straight(rng, axis_xy, k)) for i, k in enumerate(kinds)]


def random_curves(axis_xy, seed) -> list[Line]:
    rng = np.random.default_rng(seed + 1)
    kinds = ["arc"] * 40 + ["rim"] * 30 + ["wave"] * 15 + ["wave_base"] * 15
    return [_line(f"curve:{k}:{i}", _curve(rng, axis_xy, k)) for i, k in enumerate(kinds)]


# --------------------------------------------------------------------------- all of it


def cases(rig, arm_id: int) -> dict[str, list[Line]]:
    """Every test line for one arm, table frame, by set."""
    axis = rig.T_table_base(arm_id)[:2, 3]
    word_axis = rig.T_table_base(WORD_ARM)[:2, 3]
    return {"word": word(axis, word_axis), "corpus": corpus(axis),
            "lines": random_lines(axis, arm_id), "curves": random_curves(axis, arm_id)}


def base_cases(rig, arm_id: int) -> dict[str, list[Line]]:
    """The same lines in the arm's base frame, ready for the local planner."""
    return {k: [rig.to_base(arm_id, x) for x in v] for k, v in cases(rig, arm_id).items()}


def problem(rig, arm_id: int):
    """(arm, obstacles, rules, gates) for an arm leading in its phase."""
    from aris.types import DrawRules
    gates = rig.gates()
    return (rig.arm(arm_id), rig.obstacles_for(arm_id, rig.phase(ARMS[arm_id])),
            DrawRules(gates=gates), gates)


# --------------------------------------------------------------------------- measuring


def drawn_length(bunches, line_id) -> float:
    return sum(b.piece.s1 - b.piece.s0 for b in bunches if b.piece.line_id == line_id)


def per_line(lines, bunches, leftovers, stats) -> dict:
    """One row per line: what the planner did with it."""
    rows = {k: [] for k in ("id", "length", "drawn", "pieces", "single", "lean_deg", "alts",
                            "t_total", "t_graph", "t_search", "t_dense", "t_verify", "t_timing",
                            "nodes", "ik", "repairs", "widened")}
    by_line = {}
    for b in bunches:
        by_line.setdefault(b.piece.line_id, []).append(b)
    left = {}
    for x in leftovers:
        left.setdefault(x.piece.line_id, []).append(x)
    for line, st in zip(lines, stats):
        bs = by_line.get(line.id, [])
        lean = [np.linalg.norm(b.plans[0].lean, axis=1).max() for b in bs]
        rows["id"].append(line.id)
        rows["length"].append(st.length)
        rows["drawn"].append(sum(b.piece.s1 - b.piece.s0 for b in bs))
        rows["pieces"].append(len(bs))
        rows["single"].append(len(bs) == 1 and not left.get(line.id))
        rows["lean_deg"].append(np.rad2deg(max(lean, default=0.0)))
        rows["alts"].append([len(b.plans) for b in bs])
        for k, v in st.seconds.items():
            rows[f"t_{k}"].append(v)
        rows["t_total"].append(sum(st.seconds.values()))
        rows["nodes"].append(st.nodes)
        rows["ik"].append(st.ik_poses)
        rows["repairs"].append(st.repairs)
        rows["widened"].append(st.widened)
    return rows


def run(rig, arm_id: int, workers: int, sets=SETS, obstacles=None, cache_dir=None,
        settings=None):
    """Plan every set for one arm.  -> {set: (lines, bunches, leftovers, stats, wall seconds)}."""
    import time

    from aris.local import plan_detailed
    arm, obs, rules, gates = problem(rig, arm_id)
    obs = obs if obstacles is None else obstacles
    out = {}
    for name, lines in base_cases(rig, arm_id).items():
        if name not in sets:
            continue
        t = time.perf_counter()
        b, lo, st = plan_detailed(arm, lines, obs, rules, gates, workers=workers,
                                  settings=settings, cache_dir=cache_dir)
        out[name] = (lines, b, lo, st, time.perf_counter() - t)
    return out


def _pct(x, p):
    return float(np.percentile(x, p)) if len(x) else float("nan")


def report(arm_id: int, results: dict, ref=None) -> list[str]:
    """The acceptance numbers, one block per set."""
    out = []
    for name, (lines, bunches, leftovers, stats, wall) in results.items():
        r = per_line(lines, bunches, leftovers, stats)
        L, D = np.array(r["length"]), np.array(r["drawn"])
        single = np.array(r["single"])
        out.append(f"arm {arm_id} {name}: {len(lines)} lines, {L.sum():.2f} m, wall {wall:.1f} s")
        out.append(f"  drawn {D.sum() / L.sum():.4f} of the length; drawn whole in one piece: "
                   f"{single.mean():.4f} of lines, {L[single].sum() / L.sum():.4f} of length")
        pcs = np.array(r["pieces"])
        out.append(f"  pieces per line: " + ", ".join(f"{k}: {int((pcs == k).sum())}"
                                                      for k in range(0, pcs.max() + 1)))
        by = {}
        for x in leftovers:
            n, m = by.get(x.reason, (0, 0.0))
            by[x.reason] = (n + 1, m + x.piece.s1 - x.piece.s0)
        out.append("  leftovers: " + (", ".join(f"{k} {n} ({m:.3f} m)" for k, (n, m) in
                                                sorted(by.items())) or "none"))
        what = {}
        for x in leftovers:
            if x.reason == "blocked":
                name = x.detail.replace("blocked by ", "")
                what[name] = what.get(name, 0.0) + x.piece.s1 - x.piece.s0
        if what:
            out.append("  blocked by: " + ", ".join(f"{k} {m:.3f} m" for k, m in
                                                    sorted(what.items(), key=lambda t: -t[1])))
        lean = np.array(r["lean_deg"])
        out.append(f"  lines using the lean: {int((lean > 1e-9).sum())}, largest "
                   f"{lean.max():.1f} deg, median of those {_pct(lean[lean > 1e-9], 50):.1f}")
        T = np.array(r["t_total"])
        out.append(f"  seconds per line: median {_pct(T, 50):.2f}, p95 {_pct(T, 95):.2f}, worst "
                   f"{T.max():.2f}; share graph/search/dense/verify/timing " + "/".join(
                       f"{np.sum(r['t_' + k]) / T.sum():.2f}"
                       for k in ("graph", "search", "dense", "verify", "timing")))
        out.append(f"  per line: nodes median {_pct(r['nodes'], 50):.0f} p95 "
                   f"{_pct(r['nodes'], 95):.0f}; IK poses median {_pct(r['ik'], 50):.0f} p95 "
                   f"{_pct(r['ik'], 95):.0f}; repairs {int(np.sum(r['repairs']))}")
        alts = np.array([a for x in r["alts"] for a in x])
        out.append("  alternatives per piece: " + ", ".join(
            f"{k}: {int((alts == k).sum())}" for k in range(1, alts.max() + 1 if len(alts) else 1)))
        if ref is not None and f"a{arm_id}_ids" in ref:
            ids = list(ref[f"a{arm_id}_ids"])
            idx = [ids.index(x.id) for x in lines]
            old_d, old_t = ref[f"a{arm_id}_drawn"][idx], ref[f"a{arm_id}_seconds"][idx]
            less = D < old_d - 1e-3
            out.append(f"  old planner: drawn {old_d.sum() / L.sum():.4f}; seconds per line "
                       f"median {_pct(old_t, 50):.2f}, p95 {_pct(old_t, 95):.2f}, worst "
                       f"{old_t.max():.2f}; new draws less on {int(less.sum())} lines "
                       f"({(old_d - D)[less].sum():.3f} m), more on "
                       f"{int((D > old_d + 1e-3).sum())} ({(D - old_d)[D > old_d + 1e-3].sum():.3f} m)")
    return out


def figure(rig, arm_id: int, line_table: Line, path) -> None:
    """docs/modules/figures/local_example.png: the graph of one line and the route through it."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    from aris.local import Settings, polyline
    from aris.local.gates import Judge
    from aris.local.lattice import Lattice
    from aris.local.search import best_route
    arm, obs, rules, gates = problem(rig, arm_id)
    cfg = Settings()
    line = rig.to_base(arm_id, line_table)
    pts, s_pts = polyline.clean(line.points)
    s = polyline.layer_positions(float(s_pts[-1]), cfg.step)
    lat = Lattice(arm, Judge(arm, obs, gates, cfg.hand_paper_margin),
                  polyline.at(pts, s_pts, s), s, rules.lean_max, cfg)
    route = best_route(lat, cfg.lift_cost, cfg.gap_cost)
    fig, (top, graph) = plt.subplots(1, 2, figsize=(13, 5.2), width_ratios=(1, 1.6))
    axis = rig.T_table_base(arm_id)[:2, 3]
    xy = np.asarray(line_table.points)[:, :2]
    top.add_patch(plt.Rectangle(-CANVAS_HALF, *(2 * CANVAS_HALF), fc="#f4f1ea", ec="#999"))
    top.add_patch(plt.Circle(axis, 0.88, fc="none", ec="#bbb", ls="--"))
    top.plot(*axis, "k+", ms=14, mew=2)
    top.annotate(f"arm {arm_id}", axis, (6, 6), textcoords="offset points")
    colours = plt.cm.tab10.colors
    for i, run in enumerate(route.runs):
        seg = polyline.at(np.column_stack([xy, np.zeros(len(xy))]), s_pts, s[run.k0:run.k1 + 1])
        top.plot(seg[:, 0], seg[:, 1], lw=3, color=colours[i % 10])
    top.plot(*xy[0], "o", color="k", ms=5)
    top.annotate("start", xy[0], (6, -12), textcoords="offset points")
    pad = 0.25
    top.set_xlim(min(xy[:, 0].min(), axis[0]) - pad, max(xy[:, 0].max(), axis[0]) + pad)
    top.set_ylim(min(xy[:, 1].min(), axis[1]) - pad, max(xy[:, 1].max(), axis[1]) + pad)
    top.set_aspect("equal")
    top.set_xlabel("table x (m)")
    top.set_ylabel("table y (m)")
    top.set_title("the line on the paper (top view), one colour per piece")
    for i, run in enumerate(route.runs):
        _, _, _, slot = lat.params(run.k0, run.nodes[:1])
        q7_route = []
        for j, k in enumerate(range(run.k0, run.k1 + 1)):
            L = lat.layers[k]
            node = run.nodes[j]
            same = (L.slot == L.slot[node]) & (L.spin == L.spin[node]) & (L.lean == 0)
            graph.scatter(np.full(same.sum(), s[k]), lat.q7s[L.q7[same]],
                          c=np.where(L.free[same], "#9ab", "#e9b"), s=14, lw=0, zorder=1)
            q7_route.append(lat.q7s[L.q7[node]])
        spins = [np.rad2deg(lat.params(k, run.nodes[j:j + 1])[0][0]) % 360
                 for j, k in enumerate(range(run.k0, run.k1 + 1))]
        graph.plot(s[run.k0:run.k1 + 1], q7_route, "-o", color=colours[i % 10], ms=4, lw=2,
                   zorder=2, label=f"route, piece {i + 1}: IK slot {int(slot[0])}, spin "
                                   f"{spins[0]:.0f} to {spins[-1]:.0f} deg")
    for k0, k1 in route.gaps:
        graph.axvspan(s[k0], s[k1], color="#eee", zorder=0)
    graph.scatter([], [], c="#9ab", s=14, label="usable node")
    graph.scatter([], [], c="#e9b", s=14, label="inside the gates, but hits an obstacle")
    graph.set_xlabel("position along the line (m)")
    graph.set_ylabel("elbow value, joint 7 (rad)")
    graph.set_title("nodes of the route's spin and IK slot in each layer, and the route")
    graph.legend(loc="upper left", fontsize=8, framealpha=0.9)
    fig.tight_layout()
    fig.savefig(path, dpi=130)


def paper_only(rig, arm_id: int):
    from aris.types import Obstacles
    obs = problem(rig, arm_id)[1]
    return Obstacles(planes=tuple(p for p in obs.planes if p.kind == "paper"))


def explain(arm_id: int, alone: dict, real: dict, ref) -> list[str]:
    """Every line the new planner (paper only) draws less of than the old one, with what the
    new planner says about the missing stretch."""
    if ref is None or f"a{arm_id}_ids" not in ref:
        return []
    ids = list(ref[f"a{arm_id}_ids"])
    out = []
    for name, (lines, bunches, leftovers, _, _) in alone.items():
        for line in lines:
            new = drawn_length(bunches, line.id)
            old = float(ref[f"a{arm_id}_drawn"][ids.index(line.id)])
            if new < old - 1e-3:
                left = [f"{x.reason} {x.piece.s0:.3f}-{x.piece.s1:.3f} ({x.detail})"
                        for x in leftovers if x.piece.line_id == line.id]
                with_obs = drawn_length(real[name][1], line.id)
                out.append(f"  LESS {line.id}: new {new:.3f} m (with obstacles {with_obs:.3f}), "
                           f"old {old:.3f} m of {ref[f'a{arm_id}_length'][ids.index(line.id)]:.3f};"
                           f" " + "; ".join(left))
    return out


if __name__ == "__main__":
    import argparse

    from aris.rig import Rig
    ap = argparse.ArgumentParser(description="plan the fixed set, print the acceptance numbers")
    ap.add_argument("--workers", type=int, default=16)
    ap.add_argument("--arms", default="31,13")
    ap.add_argument("--sets", default=",".join(SETS))
    ap.add_argument("--figure", action="store_true", help="draw the module page's figure only")
    a = ap.parse_args()
    rig = Rig.load(ROOT / "config")
    if a.figure:
        example = [x for x in random_lines(rig.T_table_base(31)[:2, 3], 31)
                   if x.id == FIGURE_LINE][0]
        figure(rig, 31, example, ROOT / "docs" / "modules" / "figures"
               / "local_example.png")
        raise SystemExit
    ref_file = DATA / "local_reference.npz"
    ref = np.load(ref_file) if ref_file.exists() else None
    for arm_id in (int(x) for x in a.arms.split(",")):
        res = run(rig, arm_id, a.workers, a.sets.split(","))
        print("\n".join(report(arm_id, res, ref)), flush=True)
        paper = paper_only(rig, arm_id)
        alone = run(rig, arm_id, a.workers, a.sets.split(","), obstacles=paper)
        print(f"--- arm {arm_id} with only the paper as obstacle (like the old planner)")
        print("\n".join(report(arm_id, alone, ref)), flush=True)
        print("\n".join(explain(arm_id, alone, res, ref)), flush=True)
